### ISSUE TITLE
Crash with tablet pen after update to v4.1.7

### ISSUE THREAD

**Issue by capnm** [flathub/org.kde.krita#12]
The flatpack krita v4.1.7 (flatpack update) distribution crashes. For the details See
https://bugs.kde.org/show_bug.cgi?id=402155

```
flatpak info org.kde.krita
Ref: app/org.kde.krita/x86_64/stable
ID: org.kde.krita
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-12-14 12:53:28 +0000
Subject: disable arm/arm64 build (krita fails to build) (7ea73510)
Commit: 124909aa8fc12fcfc10d15ebf1c0267fa7690765e2e9b7729df007ef9de2e559
Parent: 3e442f86e7af53f1e9b4bb18953c4629af28a9c16adcdbdfcab936ff395f7776
Location: /var/lib/flatpak/app/org.kde.krita/x86_64/stable/124909aa8fc12fcfc10d15ebf1c0267fa7690765e2e9b7729df007ef9de2e559
Installed size: 239,8 MB
Runtime: org.kde.Platform/x86_64/5.11
Sdk: org.kde.Sdk/x86_64/5.11
```

**Comment by boudewijnrempt** [comment]
The issue as reported on dot.kde.org looks like the Qt 5.12 crash we fixed for 4.1.7... But from this output, it looks like this build is done with 5.11 where the crash with the double delete in QTabletEvent cannnot be present. I did verify with Arch users that the fix for Qt 5.12 is correct...

**Comment by capnm** [comment]
> it looks like this build is done with 5.11 where the crash with the double delete in QTabletEvent cannnot be present.

Strangely, I can reproduce this 100% (with flatpak uninstall / install) org.kde.krita on the current Ubuntu 18.04 and another user has already reported the same issue with Fedora 29 ¯\\_(ツ)_/¯ 
```
flatpak list -d
Ref                                        Origin  Active commit Latest commit Installed size Options       
com.uploadedlobster.peek/x86_64/stable     flathub fa981e96f3ed  -               5,7 MB       system,current
org.gimp.GIMP/x86_64/stable                flathub 1fcb2c783cf6  -             213,3 MB       system,current
org.kde.krita/x86_64/stable                flathub 124909aa8fc1  -             239,8 MB       system,current
org.freedesktop.Platform.ffmpeg/x86_64/1.6 flathub d757f762489e  -               7,7 MB       system,runtime
org.gnome.Platform/x86_64/3.28             flathub 6d1d0ebbd724  -               1,3 GB       system,runtime
org.gtk.Gtk3theme.Ambiance/x86_64/3.22     flathub 73fed99df212  -              16,3 MB       system,runtime
org.kde.KStyle.Adwaita/x86_64/5.11         flathub e57166147180  -               1,4 MB       system,runtime
org.kde.Platform/x86_64/5.11               flathub 02ede84d3591  -               1,4 GB       system,runtime
```

**Comment by eszlari** [comment]
You could produce a backtrace to help debug this:
```
$ flatpak install flathub org.kde.Sdk.Debug//5.11
$ flatpak install flathub org.kde.krita.Debug
$ flatpak run -d --command=sh org.kde.krita
$ gdb krita
(gdb) run
[trigger crash]
(gdb) bt
```
btw: @aleixpol is working on the 5.12 runtime:
https://flathub.org/builds/#/builders/2/builds/6757

**Comment by boudewijnrempt** [comment]
I'm making a new tarball with the workaround enabled for Qt 5.11.3, too. That release got a backport of the buggy commit in 5.12.

**Comment by eszlari** [comment]
commit: https://github.com/flathub/org.kde.krita/commit/901c3140d2a6b6f24e71af4190f5a5744bcff7cc

@capnm Can you confirm the fix?

**Comment by capnm** [comment]
@ebassi Yes, it works now, it doesn't crash anymore.
By the way, thanks for the flatpak debugging fu, I didn't know that!

**Comment by boudewijnrempt** [comment]
I also created an updated tarball with that patch: 4.1.7.101
