### ISSUE TITLE
cannot link krita to blender as external image editor

### ISSUE THREAD

**Issue by AT-Geist** [flathub/org.kde.krita#138]
Hi, I switched from the Krita appimage to the flatpak and was wondering if anyone
could help me link the Krita flatpak to Blender as an external image editor.

When I try this with the appimage (by giving the path to the executable), blender can open Krita 
to edit textures.

I don't know if flatpaks have an executable I can give the path to, so I put in the command instead.
Blender can't seem to run krita like this, is there a way around this?

![image](https://user-images.githubusercontent.com/68447848/208808748-d7249a97-d9ae-44e0-89dd-d8c3270a1c8d.png)
![image](https://user-images.githubusercontent.com/68447848/208808806-03d7de88-1b2b-4638-8208-c08e04c6f6a4.png)

**Comment by orowith2os** [comment]
This is a feature of flatpak, not a bug: flatpaks can't run other flatpaks unless they can escape the sandbox and have the appropriate permissions.

Blender would ideally be using the appropriate portals for opening Krita rather than relying on you specifying a command.

**Comment by AT-Geist** [comment]
Ah, that makes sense. Since I normally use Krita like this, I'll revert to using the official appimage.

Thank you for your response!
