### ISSUE TITLE
Qt Style

### ISSUE THREAD

**Issue by duartqx** [flathub/org.kde.krita#14]
Sorry for opening a issue for a thing that most people probably don't mind. But could the next update for the krita flatpak use breeze as qt style? Kdenlive flatpak uses breeze so I think krita can do so as well. Be nice.

**Comment by eszlari** [comment]
Maybe it would be a better idea, to open an issue upstream:
https://invent.kde.org/kde/krita/issues

**Comment by boudewijnrempt** [comment]
Our bug tracker is https://bugs.kde.org, but in fact breeze is explicitly disabled in Krita because it has some bugs that make Krita very hard to use.
