### ISSUE TITLE
Krita Crashes After a Few Seconds

### ISSUE THREAD

**Issue by sagedemage** [flathub/org.kde.krita#140]
# Krita Crashes After a Few Seconds

**Krita Version**: 5.1.4

## SUMMARY:
It is kind of strange that Krita crashes for some reason. I am using Gnome Desktop. The GPU is Nvidia GTX 1060. I am running on X11 (Xorg). I have a backtrace of krita crashing. There is something wrong with the flatpak version of krita since the app image of krita worked well for me.

## STEPS TO REPRODUCE
1.  Open "Show Applications" menu button on Gnome
2.  Click Krita
3.  In a few seconds, Krita crashes 

**Reproducible**: Always

## OBSERVED RESULT
Krita crashed after a few seconds.

## EXPECTED RESULT
Krita should run without crashing.

## SOFTWARE/OS VERSIONS
Linux Kernel: 6.0.0-6-amd64
Gnome Version: 42.4
Qt Version:  5.12.12

## GPU Hardware and Driver:
Nvidia Card: GeForce GTX 1060 6GB
Nvidia Driver Version: 510.108.03

## BACKTRACE:
$ flatpak run --command=sh --devel org.kde.krita
[📦 org.kde.krita ~]$ gdb /app/bin/krita
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /app/bin/krita...
(No debugging symbols found in /app/bin/krita)
(gdb) run
Starting program: /app/bin/krita 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff0299640 (LWP 16)]
[New Thread 0x7fffefa50640 (LWP 17)]
Qt: Session management error: None of the authentication protocols specified are supported
[Thread 0x7ffff0299640 (LWP 16) exited]
[New Thread 0x7ffff0299640 (LWP 18)]
Qt: Session management error: None of the authentication protocols specified are supported
[Thread 0x7ffff0299640 (LWP 18) exited]
[New Thread 0x7ffff0299640 (LWP 19)]
Qt: Session management error: None of the authentication protocols specified are supported
[Thread 0x7ffff0299640 (LWP 19) exited]
[New Thread 0x7ffff0299640 (LWP 20)]
Gtk-Message: 15:03:03.554: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:03:03.554: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[New Thread 0x7fffde2f4640 (LWP 21)]
QObject::startTimer: Timers cannot have negative intervals

**Comment by theofficialgman** [comment]
same issue on ubuntu bionic on nvidia tegra gpu 32.3.1 drivers (custom flatpak gpu driver runtime)

**Comment by travier** [comment]
This is not a backtrace. Please install the debuginfo for Krita and get a backtrace.

**Comment by sagedemage** [comment]
So, I already install org.kde.krita.Debug. Running `run` on gdb exits out of the flatpak shell. Running bt and getting backtrace is tough to do. 

I installed xfce4 to see if krita runs fine. When I click on the krita desktop icon, Krita actually runs fine on xfce. So this might be a strange bug with Gnome 42.4. For some reason, the flatpak version of krita does not want to run properly on gnome 42.4 when I click on krita's desktop icon. This seems like I would have to file a bug report to the gnome project.

**Comment by travier** [comment]
If it works while running `flatpak run org.kde.krita` then I don't think we can do something here.

**Comment by stemy2** [comment]
I have this problem for other flatpak apps, so it's not on the krita's side.
