### ISSUE TITLE
Use the FFmpeg runtime

### ISSUE THREAD

**Issue by ricvelozo** [flathub/org.kde.krita#18]
Use the FFmpeg runtime like [org.blender.Blender](https://github.com/flathub/org.blender.Blender/pull/43).

**Comment by wjt** [comment]
Regardless of the precise implementation, it would be great to have the patent-encumbered codecs split out into an optional extension so that the rest of the application can be freely redistributed.

**Comment by ricvelozo** [comment]
If Krita needs H264 encoding, it may be necessary to create an extension like [flathub/org.blender.Blender!47](https://github.com/flathub/org.blender.Blender/pull/47).
