### ISSUE TITLE
Global menu does not work anymore

### ISSUE THREAD

**Issue by ntninja** [flathub/org.kde.krita#185]
This was most likely introduced with the switch to Krita’s Qt 5.15. Blocking access to the *com.canonical.AppMenu.Registrar* D-Bus name does not work around the issue, so it is **now impossible to use the menu at all** on KDE desktops with global menu enabled.

**Comment by vulongm** [comment]
Found the fix, looks like we have to set ``QT_QPA_PLATFORMTHEME=gtk3``.

**Comment by vulongm** [comment]
Does the new build fix the global menu for you?

**Comment by ntninja** [comment]
Thank you! It’s fixed now, working better than ever! :slightly_smiling_face:
