### ISSUE TITLE
ffmpeg not bundled to render images sequence as video

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.kde.krita#2]
I tried to render my sequence of images from the menu, using the video output. Of course this option asks me to locate the file ffmpeg, which of course I have installed. However, when looking for it in the system, the option does not appear, but it does appear with the AppImage krita. I copied the ffmpeg binary into another folder, thinking that maybe, I had some kind of problem with some flatpak restriction, and when selecting it to render it is not working, but with the AppImage krita does.
So I deduce that the krita flatpak has some restriction in terms of locating files or binaries

**Comment by TingPing** [comment]
Flatpak is sandboxed so yes you can never use host binaries. This package needs to bundle `ffmpeg` which it does not currently.

**Comment by Lvaskz** [comment]
So, will never happen?

**Comment by aleixpol** [comment]
Yes, patches welcome

**Comment by TingPing** [comment]
Lots of packages bundle `ffmpeg`: https://github.com/search?q=org%3Aflathub+ffmpeg&type=Code

The hard part is figuring out the exact minimal subset of codecs that Krita needs.

**Comment by Lvaskz** [comment]
Well, Maybe asking to krita team, I guess🤔

**Comment by eszlari** [comment]
@Lvaskz I have add ffmpeg in https://github.com/flathub/org.kde.krita/commit/ffd3003c03dba95b873bc1a865f2c55e36f4d6eb, can you verify that it works now?

**Comment by Lvaskz** [comment]
Hi, I verified, it has a problem
![krita](https://user-images.githubusercontent.com/29207169/36059603-fe7bdec2-0e00-11e8-8f05-1e8e8fa9d940.png)

**Comment by Lvaskz** [comment]
Sorry, it is working now. thanks
