### ISSUE TITLE
Krita Flatpak cannot access files over SMB/gvfs

### ISSUE THREAD

**Issue by boudewijnrempt** [flathub/org.kde.krita#21]
We got this bug report: https://bugs.kde.org/show_bug.cgi?id=421418 and determined the problem probably is the flatpak. I'm not sure whether mint uses the flathub flatpak -- if not, please close this bug.

To quote:

"Whenever I try to open a file stored on a remote server, Krita simply refuses to see the path as extant.  Even when I drop the file into Krita from a file browser application.  Also, cannot find gvfs/remote mount points/remote softlinks from Krita's File Open dialogue.  It takes a while, copying to local machine just to edit to then have to manually upload back to the fileserver.

Can't find any info in FAQ about remote file access issues/protocols.

STEPS TO REPRODUCE
1. Open Krita;
2. a) Drop file from remote share into Krita; or
   b) Click File>Open and browse to /run/user/1000/gvfs...; or
   c) Click File>Open and browse to link to a gvfs mount point;
3. FAILURE

OBSERVED RESULT
"The file file:///run/user/1000/gvfs/smb-share:server=[xxxxxx],share=[xxxxxx]/Customer Data/[xxxxxx]/Website photos/Projects/[xxxxxx]/IMG_1713.JPG does not exist."

EXPECTED RESULT
File should be open ready for editing and saving as normal."

**Comment by boudewijnrempt** [comment]
Cool, thanks!

**Comment by eszlari** [comment]
No problem. Luckily, we just had this problem with FreeCAD: https://github.com/flathub/org.freecadweb.FreeCAD/pull/23

**Comment by eszlari** [comment]
Probably I should enabled this for most Qt apps, as a KDE/Plasma user you just don't notice such things.

**Comment by boudewijnrempt** [comment]
Yes, definitely.

**Comment by aleixpol** [comment]
Which code uses gvfs? Is it something krita and freecad do or something that comes higher in the stack?

**Comment by boudewijnrempt** [comment]
I would assume it's Qt, because we for sure have no special file system handling code in Krita.

**Comment by eszlari** [comment]
At first I tried to reproduce this under Ubuntu 20.04 (GNOME), but couldn't, it worked out of the box. I then tried it with the exact distribution of that user (Mint 19.2 Xfce), and there I could see it and adding `--filesystem=xdg-run/gvfs` fixed it. The difference to Ubuntu seems to stem from the old flatpak version in that Mint release (1.0.8).

**Comment by eszlari** [comment]
Unfortunately, a lot of people are still on 1.0:

https://ahayzen.com/direct/flathub.html#downloadsbyflatpakmajorstacked

**Comment by eszlari** [comment]
It's kind of ironic: flatpak gets a lot exposure by being installed by default on Mint. But then it's crippled by the fact that Mint bases their releases on Ubuntu LTS. And Canonical has certainly no interest in putting any effort into getting flatpak to work by back-porting newer releases.
