### ISSUE TITLE
Tablet offset in HiDPI mode caused by wrong version of Qt (5.14.2)

### ISSUE THREAD

**Issue by dimula73** [flathub/org.kde.krita#25]
The flatpak package ships wrong version of Qt. Krita officially supports Qt 5.12.9 only and it needs these 6 custom patches applied to Qt:

0012-Synthesize-Enter-LeaveEvent-for-accepted-QTabletEven.patch
0013-Poison-Qt-s-headers-with-a-mark-about-presence-of-En.patch
0081-Fix-no-warning-for-overwriting-files-in-non-native-d.patch
0082-Make-jp-e-g-default-extensions-context-aware.patch
0100-Fix-artifacts-when-rendering-multisubpath-dashed-QPa.patch
0101-Don-t-eat-ShortcutOverride-events-when-there-is-a-pa.patch
0110-Pass-proper-dirty-rect-in-paint-event-to-QOpenGLWidg.patch

Download link: https://invent.kde.org/graphics/krita/-/tree/master/3rdparty/ext_qt

Right now the flatpak package is not usable on HiPDI displays because of this bug caused by a regression in Qt. Setting the proposed environment variable as a workaround makes the lines dizzy.

Krita bugreport:
https://bugs.kde.org/show_bug.cgi?id=427039

Related Qt bugreport (I guess the fix to it caused a regressions actually):
https://bugreports.qt.io/browse/QTBUG-77826

**Comment by eszlari** [comment]
I see to options:

1) Apply this patches to KDE flatpak runtime. I already opened a bug report about this some time ago:
https://bugs.kde.org/show_bug.cgi?id=406449
The patches would need to be adapted for Qt 5.15.

2) We move the Krita flatpak from the KDE to the freedesktop runtime and build & bundle a patched Qt 5.12 like upstream does. As can read in the above bug report, @aleixpol is not a fan of this solution.

**Comment by aleixpol** [comment]
I wouldn't want to patch our runtime with random things that aren't accepted upstream, or even pursued as far as I know.
I prefer 2 right now as things are, I just find it sad that we need to resort to this.
