### ISSUE TITLE
Not all the languages are present in the flatpak package

### ISSUE THREAD

**Issue by dimula73** [flathub/org.kde.krita#27]
When clicking Settings->Switch Application Language only three languages are available: Russian, American English and British English. 

When opening this dialog in an AppImage version of Krita, the full list of languages is available.

I'm not sure, perhaps, other languages are installed somehow separately, when using flatpak?

**Comment by tsdgeos** [comment]
this is a flatpak "feature", just the locales supported in your system are installed, i.e. those that locale -a supports.

i.e. i get Catalan and English.

**Comment by eszlari** [comment]
`"separate-locales": "true"` could be added to the manifest to install all translations by default instead of moving them into the extension `org.kde.krita.Locale`.

**Comment by dimula73** [comment]
Well, since it is a "feature" of flatpack, let's consider this bug as invalid :)
