### ISSUE TITLE
Krita 4.1.7 on Raspberry Pi OS (Raspberry Pi 3)

### ISSUE THREAD

**Issue by basementmedia2** [flathub/org.kde.krita#30]
Hi,

i installed krita via flatpak on my raspberry pi 3.
Unfortunaltely the installed version (4.1.5) has a bug (crashes when graphic tablet pen touches the screen) .
This bug has been fixed in Version 4.1.7.

Is it possible to get my version 4.1.5 updated to 4.1.7 or higher on raspberry pi 3?

Best regards
Daniel

**Comment by basementmedia2** [comment]
Hi,

sorry, i don't know what to do with this link.
Can you give me further help how to get Version 4.1.5 to 4.1.7?

Best regards
Daniel

**Comment by eszlari** [comment]
> Hi,
> 
> sorry, i don't know what to do with this link.
> Can you give me further help how to get Version 4.1.5 to 4.1.7?
> 
> Best regards
> Daniel

Please test the build from:

https://github.com/flathub/org.kde.krita/pull/31#issuecomment-716217106

**Comment by basementmedia2** [comment]
Hi,

executing this in my terminal results in an error:

pi@raspberrypi:~ $ sudo flatpak install --user https://dl.flathub.org/build-repo/29878/org.kde.krita.flatpakref
Fehler: No such ref 'app/org.kde.krita/arm/test' in remote krita-origin

Sorry, i am a beginner with linux / Raspberry so i don't know how to proceed now and nee further help.

I am running the newest Raspberry Pi OS (32 bit) on a Raspberry Pi 3.

Would be great to get some further help.

Best wishes 
Daniel

**Comment by eszlari** [comment]
> I am running the newest Raspberry Pi OS (32 bit) on a Raspberry Pi 3.

You need the 64 bit version.
