### ISSUE TITLE
Create/Import/Export Palette Buttons don't work, crashes app.

### ISSUE THREAD

**Issue by jahed** [flathub/org.kde.krita#33]
When using the Colour Picker window, the buttons along the bottom of the Palette Picker popup don't seem to work. Clicking them does nothing (see screenshot for what I'm talking about).

Also when using the Palette Docker, the Palette Picker popup buttons do "react" to clicks but the entire app crashes immediately after.

I'm on Krita 4.4.1. Fedora 33. GNOME.

![Screenshot from 2020-11-29 14-06-56](https://user-images.githubusercontent.com/3330963/100544241-431fe880-324c-11eb-9387-6e201e0a501d.png)

**Comment by jahed** [comment]
I've just tried with the AppImage and it also doesn't work, same behaviour. So this is an upstream issue. Closing this.

**Comment by eszlari** [comment]
Thanks for confirming this with the AppImage!
