### ISSUE TITLE
Krita aarch64 broken (has non-functional editor)

### ISSUE THREAD

**Issue by theofficialgman** [flathub/org.kde.krita#430]
krita on aarch64 (tested on two systems, one nvidia jetson TX1, and one nvidia jetson orin nano) has a non-functional editor.
starting a new file the graphics preview does not change from welcom information on launch. the mouse disappears when you hover over the graphics preview area but never loads. there are no debug logs available when this happens and the application does not crash.

**Comment by theofficialgman** [comment]
@vulongm continuation of https://github.com/flathub/org.kde.krita/issues/154 
unforuntatly I never tested actually making a file (my bad). the GUi does not crash anymore but as mentioned, attempting to make a file does not work

**Comment by vulongm** [comment]
Is this a new issue on a more recent update or did it occur since #154?

**Comment by theofficialgman** [comment]
> Is this a new issue on a more recent update or did it occur since #154?

It has occurred since #154 . Likely affects all Nvidia GPUs.

**Comment by vulongm** [comment]
Got it, I wonder if this is a flatpak specific issue. I'm not sure if there's an Krita ARM package from the distro you can test as well.

**Comment by theofficialgman** [comment]
Krita from the distro (Ubuntu 22.04) works normally. The same BSP (GPU drivers) are used in both the flatpak and distro.

I think this issue likely stems from your use of opengles in QT5 on aarch64, meanwhile all distros use opengl on aarch64 for the past 10 years or so now
https://github.com/flathub/org.kde.krita/blob/f2683d157f104e3207f237c6543c77aa6b6cc815/org.kde.krita.yaml#L46-L49

@vulongm can you trigger a build with that configuration option removed and then I can test it?

**Comment by vulongm** [comment]
I do know for the official runtime they do use those flags as well. But I can try putting together a PR without it to see if that works. https://invent.kde.org/packaging/flatpak-kde-runtime/-/blob/35ca00902849ac9a3c29a9381fa3930969a60b60/org.kde.Sdk.json.in#L133

**Comment by vulongm** [comment]
@theofficialgman Does https://github.com/flathub/org.kde.krita/pull/502#issuecomment-1696110600 make any difference there?

**Comment by theofficialgman** [comment]
> @theofficialgman Does [#502 (comment)](https://github.com/flathub/org.kde.krita/pull/502#issuecomment-1696110600) make any difference there?

@vulongm yes, as expected, that build works

**Comment by theofficialgman** [comment]
> @vulongm can you trigger a build with that configuration option removed and then I can test it? Might be also worth testing x86_64 with the opengles option added on a Nvidia desktop GPU (or any other GPU) to see if the issue manifests there on anything

I am going to suggest testing this now ^. I don't have a Nvidia Desktop GPU so can't myself but I'm sure if you make a build that someone will be able to test it. Krita has a LOT of funky patches regarding GLES/GL support so I wouldn't be surprised if one of them is simply incorrect/buggy and causes the issue I have seen.

**Comment by vulongm** [comment]
@theofficialgman Are there any downsides to not building with that flag as well? We might be able to remove it if it does solve the issue

**Comment by theofficialgman** [comment]
> @theofficialgman Are there any downsides to not building with that flag as well? We might be able to remove it if it does solve the issue

on this hardware, no, and thats why distros dropped it like I said 10 years ago.
for more detail about OpenGL on aarch64 in general I will refer to you my post request that KDE runtime on flatpak implement it (they are the ONLY ones holding out and it causes many applications to break) https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/19#note_614692

**Comment by vulongm** [comment]
Got it I think we can leave that flag out in our build in that case if it ends up getting it working on more machines.
