### ISSUE TITLE
Rebase on the KDE Runtime?

### ISSUE THREAD

**Issue by travier** [flathub/org.kde.krita#44]
This is currently running on the `org.freedesktop.Platform` Runtime with a lot of Qt pacakges and framework updates missing that are in the KDE Runtime. Should this be rebase on top of this runtime?

**Comment by Doomsdayrs** [comment]
This was also mentioned in #38

**Comment by vulongm** [comment]
It was originally on KDE runtime but moved to freedesktop. Krita upstream uses an older Qt version with custom patches from what I understand. Check #26, #25 and https://invent.kde.org/graphics/krita/-/tree/master/3rdparty.

**Comment by travier** [comment]
OK, let's close this one then.

**Comment by hrj** [comment]
> It was originally on KDE runtime but moved to freedesktop. Krita upstream uses an older Qt version with custom patches from what I understand.

Is this still true for Krita 5?

**Comment by travier** [comment]
Yes

**Comment by yakushabb** [comment]
This is probably the same for the current runtime.

**Comment by vulongm** [comment]
Yes, Krita still uses their own Qt and other dependencies at https://invent.kde.org/packaging/krita-deps-management

-------- Original Message --------
