### ISSUE TITLE
Krita cannot detect system theme and application style

### ISSUE THREAD

**Issue by Randdose** [flathub/org.kde.krita#460]
Krita uses the Fusion application style and the krita dark theme, even though I have another theme and style applied.

This issue only occures when using the flatpak version of Krita, all other flatpak Qt apps use the system theme and style.

**Comment by vulongm** [comment]
Issue occurs since we use a custom Qt build from Kirta upstream and not the KDE runtime. Likely won't be able to fix currently as a result.
