### ISSUE TITLE
Krita 5.2.2 crashes when I try to use the "Save as" option

### ISSUE THREAD

**Issue by cold-distance** [flathub/org.kde.krita#525]
Hi, I saw that some Flatpak runtimes were updated yesterday and since then Krita 5.2.2 crashes when I try to use the "Save as" option. Even the "Save" option crashes the application if I try to save from a blank project.

I use Fedora Silverblue 39 with GNOME 45.5 and the Wayland session. I didn't see the same behaviour in other KDE apps like Kdenlive and Okular, so it seems specify of Krita.

I don't know what runtimes are used for Krita Flatpak. If you give me more instructions I can follow them. I share what I get booting the app from the terminal.

STEPS TO REPRODUCE
1. Open Krita 5.2.2 Flatpak.
2. Use the "Save as" option or try to "Save" from a new project.
3. You see that the app crashes.

[Bug when I try to save a file in Krita 5.2.2.txt](https://github.com/flathub/org.kde.krita/files/14667795/Bug.when.I.try.to.save.a.file.in.Krita.5.2.2.txt)
![Captura desde 2024-03-20 13-03-21](https://github.com/flathub/org.kde.krita/assets/43167050/7d233d61-1aa7-4868-89ab-20c6604f166d)

**Comment by SteffenDuenner** [comment]
I'm getting the same error message as the original poster on Linux Mint 21.3 but running an X session, not Wayland.

`(krita:2): GLib-GIO-ERROR **: 17:22:52.361: No GSettings schemas are installed on the system`

Krita crashes with this message every time it tries to open a file dialogue (File > Open, File > Save As, Layer > Import > Import Layer, ...). Not only a "Save As" dialogue.

Dragging and dropping images on the GUI to add layers or images works as expected, though.

**Comment by lboekhorst** [comment]
I am having the same issue running Pop!_OS 22.04 LTS / GNOME 42.9 / X11. I also observe it crashes for every interaction which involves a file picker.

**Comment by oqipoDev** [comment]
I am getting identical terminal output to cold-distance (minus Wayland related messages), it started this morning.

Upon reading the error message, I thought that the issue might be resolved by manually specifying the `XDG_DATA_DIRS` environment variable to `/usr/local/share`. Unfortunately, although the error message goes away at the time of the crash, well, it's still crashing, so it might be unrelated.

After doing that, instead of the last error I get these warnings and a GTK error:

```
(krita:2): Gtk-WARNING **: 23:56:26.728: Could not find the icon 'user-home-symbolic-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
	http://icon-theme.freedesktop.org/releases

(krita:2): Gtk-WARNING **: 23:56:26.729: Could not load a pixbuf from /org/gtk/libgtk/icons/16x16/status/image-missing.png.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: No se ha reconocido el formato de imagen del archivo (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:../gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/16x16/status/image-missing.png: No se ha reconocido el formato de imagen del archivo (gdk-pixbuf-error-quark, 3)
```

Meanwhile, the `~/.var/app/org.kde.krita/data/krita.log` file offers little help. All entries look like this, but with different date and hour:
```
SESSION: 20 Mar 2024 23:39:20 -0600. Executing krita

Krita Version: 5.2.2, Qt version compiled: 5.15.7, loaded: 5.15.7. Process ID: 2
-- -- -- -- -- -- -- --
20 Mar 2024 23:39:20 -0600: Style: fusion. Available styles: Windows, Fusion
20 Mar 2024 23:39:21 -0600: Database is up to date. Version: 0.0.17, created by Krita 5.1.5, at mar oct. 10 19:51:48 2023

KRITA DID NOT CLOSE CORRECTLY
```

I don't know where to go from here, so for now, I'll just let this comment hoping the issue gets resolved.

Some other info:

APT packages upgraded this week:
```
libsynctex2:amd64 (2021.20210626.59705-1ubuntu0.1, 2021.20210626.59705-1ubuntu0.2)
libldap-common:amd64 (2.5.16+dfsg-0ubuntu0.22.04.2, 2.5.17+dfsg-0ubuntu0.22.04.1)
libkpathsea6:amd64 (2021.20210626.59705-1ubuntu0.1, 2021.20210626.59705-1ubuntu0.2)
libexpat1:amd64 (2.4.7-1ubuntu0.2, 2.4.7-1ubuntu0.3)
libexpat1:i386 (2.4.7-1ubuntu0.2, 2.4.7-1ubuntu0.3)
libldap-2.5-0:amd64 (2.5.16+dfsg-0ubuntu0.22.04.2, 2.5.17+dfsg-0ubuntu0.22.04.1)
libldap-2.5-0:i386 (2.5.16+dfsg-0ubuntu0.22.04.2, 2.5.17+dfsg-0ubuntu0.22.04.1)
xxd:amd64 (2:8.2.3995-1ubuntu2.15, 2:8.2.3995-1ubuntu2.16)
vim-common:amd64 (2:8.2.3995-1ubuntu2.15, 2:8.2.3995-1ubuntu2.16)
bash:amd64 (5.1-6ubuntu1, 5.1-6ubuntu1.1)
vim-tiny:amd64 (2:8.2.3995-1ubuntu2.15, 2:8.2.3995-1ubuntu2.16)
```

System info:

- Pop!_OS 22.04 LTS (64-bit)
- GNOME 42.9
- X11

**Comment by SreckoM** [comment]
Same here, can not use Krita at this stage.

**Comment by bbhtt** [comment]
This should be fixed by https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/18580

**Comment by bbhtt** [comment]
should be fixed now

**Comment by cold-distance** [comment]
I can save as usual now. Thanks.
