### ISSUE TITLE
Most of features are disabled in Krita 5.2.3 if you don't select any layer after opening an existing image or project (GNOME 46, Wayland and openSUSE Aeon)

### ISSUE THREAD

**Issue by cold-distance** [flathub/org.kde.krita#538]
Hi, I saw that Krita was recently update to the 5.2.3 version. I like the new splash, but many of the most important features of the app are now disabled.

[Grabación de pantalla desde 2024-07-02 17-45-34.webm](https://github.com/flathub/org.kde.krita/assets/43167050/cfcff44a-ec56-4181-abfe-61ff4a0e5a8e)

**Comment by vulongm** [comment]
Is that happening with a new file too? Can't seem to reproduce it currently
![image](https://github.com/flathub/org.kde.krita/assets/50088314/e71bcbb2-5356-4221-a283-caacd6aa0703)

**Comment by cold-distance** [comment]
If I create a new blank project, the options are enabled, but if I open an existing image or Krita project, the options are showed disabled. I mainly use Krita for manipulating exiting images, not to create from scratch.

After doing some more research, I see that the root of the problem is that there are no layers selected by default.

[Grabación de pantalla desde 2024-07-03 17-44-55.webm](https://github.com/flathub/org.kde.krita/assets/43167050/7157cab3-e5c1-45eb-b7fd-65601d1a8560)

**Comment by vulongm** [comment]
Is the issue also occurring with the AppImage? Might be an upstream change if not related to the flatpak.

**Comment by luroc** [comment]
Can confirm that this issue is present in the arch packaged version.

**Comment by vulongm** [comment]
Looks like this could be related to Krita related changes not connected to the packaging, might be able to ask if this is intended on the forums https://krita.org/en/report-a-bug/
