### ISSUE TITLE
Krita UI very small

### ISSUE THREAD

**Issue by LithRakoon** [flathub/org.kde.krita#56]
Hello!

when using krita (flatpak version) the ui krita is VERY small not useable in the slightest, 
i have tried krita (native package) and in that version everything works normally

i have reproduced this on fedora 35 and arch linux
all tested on x11

krita flatpak
![image](https://user-images.githubusercontent.com/41258148/162990737-5ec5641e-0982-4b37-aaee-b3e353788479.png)

**Comment by vulongm** [comment]
Are you able to reproduce the issue on the AppImage Krita has?

**Comment by LithRakoon** [comment]
yes!

**Comment by vulongm** [comment]
Might be due to the older version of Qt will have to check with upstream.

**Comment by vulongm** [comment]
Under settings and configure Krita are you able to see if Hi-DPI is enabled here?
![image](https://user-images.githubusercontent.com/50088314/183228373-9f78964f-a0f8-48c8-8521-c18351a5217a.png)

**Comment by ntninja** [comment]
Also reproducible on Wayland/KDE, manually forcing a UI scale factor by running this works at least (where 1.35 is the 135% set in the systemsettings display configuration section):
`flatpak override --user --env=QT_SCALE_FACTOR=1.35 org.kde.krita`

Also, Krita 5.2 will use https://invent.kde.org/szaman/qt5/-/tree/krita/5.15 for its Qt, maybe upgrading to that is going to help?

**Comment by adsick** [comment]
@vulongm why is the issue closed?

**Comment by vulongm** [comment]
@adsick Are you still seeing the issue on the current flathub build?

**Comment by adsick** [comment]
@vulongm I am using Appimage/Windows executable versions

**Comment by ntninja** [comment]
This issue has been resolved by the switch, but there is a new one introduced that is arguably worse: #185.
