### ISSUE TITLE
Since update to Krita 4.0.3 there is no maximize button and vertical scaling does not work

### ISSUE THREAD

**Issue by juxi500** [flathub/org.kde.krita#6]
Hello,

since update to version 4.0.3, Krita flatpak no longer offers maximize button and Krita window can't be scaled vertically. As you can see it on the screenshot, it's window is bigger than my screen and I cannot fit it in properly (it can't be resized on vertical axis, it only works on horizontal).

flatpak 0.8.8, EL7.5, 200% (hi-dpi) scaling turned on

![krita_bug](https://user-images.githubusercontent.com/38837830/40252678-62065d72-5add-11e8-9472-a2a62f49841e.png)

**Comment by juxi500** [comment]
It seems that this bug is only present when in `Settings - Configure Krita - General - Window - Enable Hi-Dpi Support` button is checked. When I uncheck this button vertical scaling works and maximize button also appears.

**Comment by eszlari** [comment]
Does the official AppImage exhibit the same behavior? https://download.kde.org/stable/krita/4.0.3/krita-4.0.3-x86_64.appimage
Then you should file a bug upstream: https://bugs.kde.org/

**Comment by juxi500** [comment]
official AppImage works as expected for me (all the buttons are there, even in hi-dpi mode)

**Comment by juxi500** [comment]
when I compare flatpak and appimage side by side there are even more differences - for example size of all fonts is bigger in flatpak version (in appimage the fonts look more "natural")

**Comment by eszlari** [comment]
Try these environment variables and see how they affect scaling:
```
QT_SCREEN_SCALE_FACTORS=1.0 to 3.0
QT_AUTO_SCREEN_SCALE_FACTOR=0 or 1
```

**Comment by juxi500** [comment]
- with `QT_SCREEN_SCALE_FACTORS=1.0` it is the same as before (with no env variables), still no maximize button
- with `QT_SCREEN_SCALE_FACTORS=2.0` everything is 2x times bigger than before, still no maximize button
- with `QT_SCREEN_SCALE_FACTORS=3.0` everything is 3x times bigger than before, still no maximize button

- with `QT_AUTO_SCREEN_SCALE_FACTOR=0` the setting: `Settings - Configure Krita - General - Window - Enable Hi-Dpi Support` has no effect when checked, in other words, when `QT_AUTO_SCREEN_SCALE_FACTOR=0` is applied, hi-dpi scaling does not work at all, but maximize button is present
- with `QT_AUTO_SCREEN_SCALE_FACTOR=1`  it is the same as before (with no env variables), still no maximize button

- combination of `QT_AUTO_SCREEN_SCALE_FACTOR=0` with `QT_SCREEN_SCALE_FACTORS=2.0` gives the same result as Krita when run with no env variables, still no maximize button

**Comment by eszlari** [comment]
Maybe it's caused by your flatpak version (0.8.8), which is quite outdated.

**Comment by juxi500** [comment]
Well it is the latest available package for EL7.5. And all other apps work without issues on my system (Blender, Darktable, OBS, LibreOffice...) Also Krita worked fine before update to 4.0.3. Maybe @alexlarsson could know what is cause of this problem?

**Comment by eszlari** [comment]
How do other Qt based apps behave? (kdenlive, openshot, shotcut, vlc)

**Comment by juxi500** [comment]
For example OBS Studio, which uses KDE, works without issues, Krita also worked without issues before this update :/

**Comment by eszlari** [comment]
@juxi500 I updated to Qt 5.11, does this help?

**Comment by eszlari** [comment]
> (org.kde.krita - 4.2.0 alpha)

That's not the version on Flathub?!

**Comment by juxi500** [comment]
sorry, I accidentally installed it from kdeapps flatpak repo... I am going to try also the flathub versuib and I will let you know

**Comment by juxi500** [comment]
ok, flathub (this) version seems working fine too :)
