### ISSUE TITLE
Crash when exporting to TIFF

### ISSUE THREAD

**Issue by dirtyfingers** [flathub/org.kde.krita#7]
openSUSE 15.0
Flatpak 0.10.4

Ref: app/org.kde.krita/x86_64/stable
ID: org.kde.krita
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2018-06-27 15:02:09 +0000
Subject: update to krita 4.1.0 (26546280)
Commit: 11b22235414bd9c30eb5cc60817c4f7152c0d235509c90de92d75d0905e1b271
Parent: 910a58aa6234a32d650b751998e5b32c9da3039dad7971ce77e6646a66a5e0ba
Location: /var/lib/flatpak/app/org.kde.krita/x86_64/stable/11b22235414bd9c30eb5cc60817c4f7152c0d235509c90de92d75d0905e1b271
Installed size: 224.2 MB
Runtime: org.kde.Platform/x86_64/5.10

**.tif image successfully saved, though.**

openSUSE version of krita (4.0.3-lp150.1.1) doesn't have this problem.

Messages: 
```
QLayout: Attempting to add QLayout "" to QWidget "", which already has a layout
QMetaObject::indexOfSignal: signal selectionChanged() from KoSelectedShapesProxy redefined in KisSelectedShapesProxy
QMetaObject::indexOfSignal: signal selectionChanged() from KoSelectedShapesProxy redefined in KisSelectedShapesProxy
ASSERT failure in QCoreApplication::sendEvent: "Cannot send events to objects owned by a different thread. Current thread 0x0xa2832b0. Receiver '' (of type 'KisImage') was created in thread 0x0x25d9930", file kernel/qcoreapplication.cpp, line 589
```

**Comment by eszlari** [comment]
https://bugs.kde.org/show_bug.cgi?id=397422

**Comment by dirtyfingers** [comment]
Updated org.kde.krita/x86_64/stable and org.kde.Platform/x86_64/5.11 from flathub today. No longer crashes. Thank you!
