### ISSUE TITLE
Update from 5.10 SDK

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.kde.krita#8]
I see the manifest uses the KDE 5.10 SDK which is based upon Qt 5.10. This is now out of security support and won't recieve further updates. It'd be good to move to either the 5.9 lts or the newer and fresher 5.11 SDK.

**Comment by eszlari** [comment]
I had problems building sip/pyqt for 5.11. I will try to get it built and if it does work, switch to 5.9.

**Comment by aleixpol** [comment]
I managed to build pyqt with qt 5.11 here https://github.com/aleixpol/qgis-flatpak

**Comment by eszlari** [comment]
> I managed to build pyqt with qt 5.11 here https://github.com/aleixpol/qgis-flatpak

This manifest builds sip 4.19.8 & PyQt 5.9.2.

 I tried to build sip 4.19.12 &  PyQt 5.11.2, always getting:
```
Error: Unable to import PyQt5.sip. Make sure you have configured SIP to create
a private copy of the sip module.
```
I did pass `--sip-module PyQt5.sip` to sip, but no *.sip-files are getting built.

**Comment by eszlari** [comment]
https://github.com/flathub/org.kde.krita/commit/f402f205485e00718ee8a8760aa2259df8e0c8de
