### ISSUE TITLE
License shows as "proprietary"

### ISSUE THREAD

**Issue by CWhyMedia** [flathub/org.kde.krita#9]
When using GNOME Software to access software from Flathub, in the Details section, it says the license is proprietary, which is not true -- it uses the GPL. How can that get fixed?

![screenshot from 2018-09-14 16-48-53](https://user-images.githubusercontent.com/42078598/45574455-1a170700-b83e-11e8-9b4b-aa3b4d1e0ce1.png)

**Comment by TingPing** [comment]
Hmm, seems fine: https://github.com/KDE/krita/blob/master/krita/org.kde.krita.appdata.xml#L6

**Comment by nedrichards** [comment]
That -only isn't the latest SPDX but I know that g-s and appstream have had differences and views there about how quickly to chase that but yeah, I'd want to intvestigate the issue in GNOME Software upstream first.

**Comment by CWhyMedia** [comment]
I'm looking at some other apps now... Shotcut (GPLv3) also shows "proprietary", while GIMP (GPL and WebTorrent show Free and specify the license. This has got to be an issue with the version of GNOME Software I'm using, since I'm on CentOS. I'll close this, thanks!
