### ISSUE TITLE
Update Flathub's 'Donate' button for Krita to the new page

### ISSUE THREAD

**Issue by ifeeltiredboss** [flathub/org.kde.krita#97]
1. Go to https://beta.flathub.org/apps/details/org.kde.krita
2. Click Donate

Current behavior:
User taken to https://krita.org/en/support-us/donations/

Expected behavior:
User taken to https://fund.krita.org/

**Comment by travier** [comment]
This needs to be changed here: https://invent.kde.org/graphics/krita/-/blob/master/krita/org.kde.krita.appdata.xml#L276

Can you file a bug report upstream to Krita or submit a PR on Invent directly? Thanks

**Comment by ifeeltiredboss** [comment]
Thanks @travier, I figured out where it needs to be changed but I do not have KDE account and I don't want to create one. There is no option to sign up with GitHub either.

**Comment by travier** [comment]
Let's keep this open until we get to it.

**Comment by vulongm** [comment]
Is fund.krita officially the new page? I notice the krita.org site still links to that page for their donate button for one time donation options but also mention the fund.krita site for monthly.

**Comment by ifeeltiredboss** [comment]
From fund.krita.org:
> ** The donation amount displayed on this page also include the donation from our [old system](https://krita.org/en/support-us/donations/).

**Comment by travier** [comment]
Filling a bug upstream is still the best way to clarify things as upstream devs will know better which one they should have there and it needs to be changed upstream anyway.

**Comment by vulongm** [comment]
Looks like the page still exists as part of the site redesign, but does reference the monthly fund option as well now.
![image](https://github.com/flathub/org.kde.krita/assets/50088314/e8091d1a-c233-4e8a-984f-b0b6a8a61600)
